# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [1]:
# Your code goes here
import pandas as pd

url1='https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv'
url2='https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv'

file0=pd.read_csv('labday2.csv')
df1=pd.read_csv(url1)
df2=pd.read_csv(url2)

In [2]:
file1=df1.copy()
display(file1.info())
file1.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   996 non-null    object
 1   ST                         996 non-null    object
 2   GENDER                     991 non-null    object
 3   Education                  996 non-null    object
 4   Customer Lifetime Value    992 non-null    object
 5   Income                     996 non-null    int64
 6   Monthly Premium Auto       996 non-null    int64
 7   Number of Open Complaints  996 non-null    object
 8   Total Claim Amount         996 non-null    float64
 9   Policy Type                996 non-null    object
 10  Vehicle Class              996 non-null    object
dtypes: float64(1), int64(2), object(8)
memory usage: 85.7+ KB

None

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount,Policy Type,Vehicle Class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,633.6,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,547.2,Special Auto,SUV

In [3]:
file2=df2.copy()
display(file2.info())
file2=df2.copy()
file2.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7070 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   7070 non-null   object
 1   State                      7070 non-null   object
 2   Customer Lifetime Value    7070 non-null   float64
 3   Education                  7070 non-null   object
 4   Gender                     7070 non-null   object
 5   Income                     7070 non-null   int64
 6   Monthly Premium Auto       7070 non-null   int64
 7   Number of Open Complaints  7070 non-null   int64
 8   Policy Type                7070 non-null   object
 9   Total Claim Amount         7070 non-null   float64
 10  Vehicle Class              7070 non-null   object
dtypes: float64(2), int64(3), object(6)
memory usage: 607.7+ KB

None

,Customer,State,Customer Lifetime Value,Education,Gender,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Total Claim Amount,Vehicle Class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car

In [4]:
#df.rename(columns={"old_column_name1": "new_column_name1", "old_column_name2": "new_column_name2",...})
file1.rename(columns={'ST': 'State','ST': 'State'}, inplace=True)
file1.columns= file1.columns.map(lambda x:x.lower())
file2.columns= file2.columns.map(lambda x:x.lower())
print(file1.columns)
print(file2.columns)

Index(['customer', 'state', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'total claim amount', 'policy type', 'vehicle class'],
      dtype='object')
Index(['customer', 'state', 'customer lifetime value', 'education', 'gender',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'total claim amount', 'vehicle class'],
      dtype='object')

In [5]:
#organizing the tables so they have the same order, rearranging the column order for file 2 columns according to file 1
new_order = file1.columns

file2 = file2[new_order]
display(file1.head(1))
display(file2.head(1))

,customer,state,gender,education,customer lifetime value,income,monthly premium auto,number of open complaints,total claim amount,policy type,vehicle class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,633.6,Personal Auto,Four-Door Car

,customer,state,gender,education,customer lifetime value,income,monthly premium auto,number of open complaints,total claim amount,policy type,vehicle class
0,SA25987,Washington,M,High School or Below,3479.137523,0,104,0,499.2,Personal Auto,Two-Door Car

In [6]:
df0=file0.copy()
df0.head(1)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,F,Master,793690,0,1000,0,Personal Auto,Four-Door Car,3

In [7]:
#now we concatenate the files 
df=pd.concat([file1, file2], axis=0).reset_index(drop=True)
#we check if the number of total rows is correct
display(df.info())
#we check how it look the labels
df.head(1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8066 entries, 0 to 8065
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   8066 non-null   object
 1   state                      8066 non-null   object
 2   gender                     8061 non-null   object
 3   education                  8066 non-null   object
 4   customer lifetime value    8062 non-null   object
 5   income                     8066 non-null   int64
 6   monthly premium auto       8066 non-null   int64
 7   number of open complaints  8066 non-null   object
 8   total claim amount         8066 non-null   float64
 9   policy type                8066 non-null   object
 10  vehicle class              8066 non-null   object
dtypes: float64(1), int64(2), object(8)
memory usage: 693.3+ KB

None

,customer,state,gender,education,customer lifetime value,income,monthly premium auto,number of open complaints,total claim amount,policy type,vehicle class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,633.6,Personal Auto,Four-Door Car

In [8]:
df.columns= df.columns.str.replace(' ','_')

#organizing the tables so they have the same order, rearranging the column order for file 2 columns according to file 1
new_or = df.columns
df0 = df0[new_or]
#we check if columns of both datasets have the same names
sorted(df.columns) == sorted(df0.columns)

True

In [9]:
#before concatenating, we need to clean the df data as the df0 (from previous lab) is already clean.
# Gender standarization
#gender={'Femal':'F', 'Male':'M', 'female':'F'}
#df.gender=df.gender.map(gender)
df.gender.unique()

array(['F', 'M', nan, 'female', 'Male'], dtype=object)

In [10]:
#we fix the naming to aling values
df.gender=df.gender.map(lambda x:
                'F'if isinstance(x,str) and x[0].lower()=='f' else
                'M' if isinstance(x,str) and x[0].lower()=='m'else
                x)
#we check if columns of both datasets have the same unique values for the column
#for now without considering NaN
sorted(df.gender.dropna().unique()) == sorted(df0.gender.dropna().unique())

True

In [11]:
df.state.unique()

array(['Arizona', 'California', 'Oregon', 'Nevada', 'Washington', 'AZ'],
      dtype=object)

In [12]:
#we fix the naming to aling values
df.state=df.state.replace('AZ','Arizona')
#we check if columns of both datasets have the same unique values for the column
#for now without considering NaN
sorted(df.state.dropna().unique()) == sorted(df0.state.dropna().unique())

True

In [13]:
df.education.unique()

array(['Bachelor', 'Master', 'College', 'Doctor', 'Bachelors',
       'High School or Below'], dtype=object)

In [14]:
#we fix the naming to aling values
df.education=df.education.replace('Bachelors','Bachelor')
#we check if columns of both datasets have the same unique values for the column
#for now without considering NaN
sorted(df.education.dropna().unique()) == sorted(df0.education.dropna().unique())

True

In [15]:
df.customer_lifetime_value.unique()

array(['323912.47%', '462680.11%', '899704.02%', ..., 8163.890428,
       7524.442436, 2611.836866], shape=(7239,), dtype=object)

In [16]:
#In Customer Lifetime Value, delete the % character
df.customer_lifetime_value=df.customer_lifetime_value.dropna().str.replace('%','',regex=False)

In [17]:
df.vehicle_class.unique()

array(['Four-Door Car', 'SUV', 'Two-Door Car', 'Luxury Car', 'Sports Car',
       'Luxury SUV'], dtype=object)

In [18]:
df.vehicle_class= df.vehicle_class.replace({
    "Sports Car": 'Luxury',
    "Luxury SUV": 'Luxury',
    "Luxury Car": 'Luxury'})
#we check if columns of both datasets have the same unique values for the column
#for now without considering NaN
sorted(df.vehicle_class.dropna().unique()) == sorted(df0.vehicle_class.dropna().unique())

True

In [19]:
#we check which columns have different types:
df.apply(lambda col: col.dtype)==df0.apply(lambda col: col.dtype)

customer                      True
state                         True
gender                        True
education                     True
customer_lifetime_value      False
income                        True
monthly_premium_auto          True
number_of_open_complaints    False
total_claim_amount           False
policy_type                   True
vehicle_class                 True
dtype: bool

In [26]:
#let's check for null
df.isnull()
#for the rows with nulls in all columns we drop
df[df.isnull()].all(axis=1)
df=df.dropna(how='all')

In [34]:
#let see if it worked: and yes it did.
df.isnull().sum()

customer                        0
state                           0
gender                          0
education                       0
customer_lifetime_value      7074
income                          0
monthly_premium_auto            0
number_of_open_complaints       0
total_claim_amount              0
policy_type                     0
vehicle_class                   0
dtype: int64

In [35]:
#let's fill gender column with the mode
df.gender=df.gender.fillna(df.gender.mode()[0])
df.gender.isnull().sum()

np.int64(0)

In [93]:
#df[df.customer_lifetime_value.isnull()]
display(df.policy_type.unique())
life_df= df[df.customer_lifetime_value.isnull()==False]
life_df.customer_lifetime_value=life_df.customer_lifetime_value.astype(float)
personal_mode=round(life_df[life_df.policy_type=='Personal Auto'].customer_lifetime_value.mean())
special_mode=round(life_df[life_df.policy_type=='Special Auto'].customer_lifetime_value.mean())
corp_mode=round(life_df[life_df.policy_type=='Corporate Auto'].customer_lifetime_value.mean())

#filling the column customer value
fill_map={'Personal Auto': personal_mode,'Special Auto': special_mode,
          'Corporate Auto': corp_mode}

for policy,value in fill_map.items():
    mask=df.policy_type==policy
    df.loc[mask,'customer_lifetime_value']= df.loc[mask,'customer_lifetime_value'].fillna(value)

display(df.customer_lifetime_value.isnull().sum())

array(['Personal Auto', 'Special Auto', 'Corporate Auto'], dtype=object)

np.int64(0)

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8066 entries, 0 to 8065
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   8066 non-null   object
 1   state                      8066 non-null   object
 2   gender                     8066 non-null   object
 3   education                  8066 non-null   object
 4   customer_lifetime_value    8066 non-null   object
 5   income                     8066 non-null   int64
 6   monthly_premium_auto       8066 non-null   int64
 7   number_of_open_complaints  8066 non-null   object
 8   total_claim_amount         8066 non-null   float64
 9   policy_type                8066 non-null   object
 10  vehicle_class              8066 non-null   object
dtypes: float64(1), int64(2), object(8)
memory usage: 693.3+ KB

In [95]:
# Customer lifetime value should be integer to match the other dataframe

df.customer_lifetime_value=round(df.customer_lifetime_value.astype(float))
df.customer_lifetime_value=df.customer_lifetime_value.astype(int)
df.customer_lifetime_value.dtype

dtype('int64')

In [96]:
#file0 which is the same df0 now, it was cleaned in the lab before but let's check if is clean with nulls
#let's check for null
display(df0.isnull().sum())
#as this was the last cleaning step from the previous lab, it is inferred the dataset is clean now.

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
total_claim_amount           0
policy_type                  0
vehicle_class                0
dtype: int64

In [97]:
# Next column dtype change, should be integer to match the other dataframe
df.total_claim_amount=df.total_claim_amount.astype(int)
df.total_claim_amount.dtype

dtype('int64')

In [101]:
# Number of open complaints should be integer to match the other dataframe
df.number_of_open_complaints

0       1/0/00
1       1/0/00
2       1/0/00
3       1/1/00
4       1/0/00
         ...
8061         0
8062         0
8063         3
8064         0
8065         0
Name: number_of_open_complaints, Length: 8066, dtype: object

In [102]:
#take the middle number only as previous lab cleaning file0 or df0
df.number_of_open_complaints=df.number_of_open_complaints.str.split('/').map(lambda x: x[1] if isinstance(x,list) else x )
df.number_of_open_complaints

0         0
1         0
2         0
3         1
4         0
       ...
8061    NaN
8062    NaN
8063    NaN
8064    NaN
8065    NaN
Name: number_of_open_complaints, Length: 8066, dtype: object

In [117]:
display(df.number_of_open_complaints.isnull().sum())
#we fill with mean
mean_comp=round(df[df.number_of_open_complaints.isnull()==False].number_of_open_complaints.astype(int).mean())
df.number_of_open_complaints=df.number_of_open_complaints.fillna(mean_comp)
#check for null values
display(df.number_of_open_complaints.isnull().sum())

np.int64(0)

np.int64(0)

In [118]:
#now that there are no more nan we convert to int
df.number_of_open_complaints=df.number_of_open_complaints.astype(int)
df.number_of_open_complaints.dtype

dtype('int64')

In [119]:
#we check now if all columns have same dtype
df.apply(lambda col: col.dtype)==df0.apply(lambda col: col.dtype)

customer                     True
state                        True
gender                       True
education                    True
customer_lifetime_value      True
income                       True
monthly_premium_auto         True
number_of_open_complaints    True
total_claim_amount           True
policy_type                  True
vehicle_class                True
dtype: bool

In [120]:
#now we concatenate
# Concatenate the sales, and sales_2 vertically (along rows)
pd.concat([df, df0], axis=0).reset_index(drop=True)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,total_claim_amount,policy_type,vehicle_class
0,GS98873,Arizona,F,Bachelor,323912,16061,88,0,633,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680,79487,114,0,547,Special Auto,SUV
2,MY31220,California,F,College,899704,54230,112,0,537,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706,71210,214,1,1027,Personal Auto,Luxury
4,WH52799,Arizona,F,College,380812,94903,94,0,451,Corporate Auto,Two-Door Car
...,...,...,...,...,...,...,...,...,...,...,...
9132,TM65736,Oregon,F,Master,305955,38644,78,1,361,Personal Auto,Four-Door Car
9133,VJ51327,California,F,High School or Below,2031500,63209,102,2,207,Personal Auto,SUV
9134,GS98873,Arizona,F,Bachelor,323912,16061,88,0,634,Personal Auto,Four-Door Car
9135,CW49887,California,F,Master,462680,79487,114,0,547,Special Auto,SUV
9136,MY31220,California,F,College,899704,54230,112,0,538,Personal Auto,Two-Door Car

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [121]:
# Your code goes here
import pandas as pd
url_1='https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv'

datf=pd.read_csv(url_1)

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [122]:
#Aim: which sales channel brought the most sales in terms of total revenue

In [123]:
sales=datf.copy()
display(sales.info())
sales.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  object
 2   state                          10910 non-null  object
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10910 non-null  object
 5   coverage                       10910 non-null  object
 6   education                      10910 non-null  object
 7   effective_to_date              10910 non-null  object
 8   employmentstatus               10910 non-null  object
 9   gender                         10910 non-null  object
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  object
 12  marital_status                 10910 non-null  object
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10910 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10910 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  object
 19  policy                         10910 non-null  object
 20  renew_offer_type               10910 non-null  object
 21  sales_channel                  10910 non-null  object
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10910 non-null  object
 24  vehicle_size                   10910 non-null  object
 25  vehicle_type                   10910 non-null  object
 26  month                          10910 non-null  int64
dtypes: float64(4), int64(6), object(17)
memory usage: 2.2+ MB

None

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1

In [124]:
#Checking data values, organisation and null values
sales['unnamed:_0'].unique() # this seems like indexes

array([    0,     1,     2, ..., 10907, 10908, 10909], shape=(10910,))

In [125]:
#Using pivot, create a summary table showing the total revenue for each sales channel
#(branch, call center, web, and mail).

In [127]:
#we will calculate revenue as:
sales['revenue'] = round(sales.customer_lifetime_value -sales.total_claim_amount)
sales.head(1)

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month,revenue
0,0,DK49336,Arizona,4809.21696,No,Basic,College,2011-02-18,Employed,M,...,Corporate Auto,Corporate L3,Offer3,Agent,292.8,Four-Door Car,Medsize,A,2,4516.0

In [130]:
sales_piv = sales.pivot_table(
    index="sales_channel", 
    values="revenue",
    aggfunc="sum",
)
display(sales_piv)

                  revenue
sales_channel
Agent          31247679.0
Branch         23058004.0
Call Center    16437680.0
Web            11991055.0

In [132]:
#Analyze the resulting table to draw insights
print(f"the branch that has the highest revenue is the Agent channel with a revenue of {sales_piv.revenue[0]}")

the branch that has the highest revenue is the Agent channel with a revenue of 31247679.0

/var/folders/y7/p6n8z7nn4fs88vn9n57nxbh40000gn/T/ipykernel_1941/1697612152.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"the branch that has the highest revenue is the Agent channel with a revenue of {sales_piv.revenue[0]}")

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [137]:
sales_muliindex=['gender','education']

custogender_piv = sales.pivot_table(
    index=sales_muliindex, 
    values="customer_lifetime_value",
    aggfunc="mean",
)
display(custogender_piv)

                             customer_lifetime_value
gender education
F      Bachelor                          7874.269478
       College                           7748.823325
       Doctor                            7328.508916
       High School or Below              8675.220201
       Master                            8157.053154
M      Bachelor                          7703.601675
       College                           8052.459288
       Doctor                            7415.333638
       High School or Below              8149.687783
       Master                            8168.832659

In [139]:
#from the table above, one can infer that among females with High School or Below 
#are actually the ones bringing more customer value.
#for the case of men, is the opposite, the men with the hight level of education
#like Master are the ones bringing more customer lifetime value.

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [ ]:
# Your code goes here